In [1]:
import hydra
from hydra import compose, initialize
from omegaconf import OmegaConf
from pathlib import Path
import pandas as pd 
import numpy as np
from hydra.utils import to_absolute_path as abspath
import geopandas

Load the proper configuration files for Hydra

In [2]:
initialize(version_base=None, config_path="./notebook.yaml", job_name="loadRaw")
cfg = compose(config_name="notebook", overrides=[])
print(OmegaConf.to_yaml(cfg))

process:
  use_columns:
  - col1
  - col2
model:
  name: model1
raw:
  path: data/raw/
processed:
  dir: data/processed
  name: processed.csv
  path: ${processed.dir}/${processed.name}
final:
  dir: data/final
  name: final.csv
  path: ${final.dir}/${final.name}

In [5]:
@hydra.main(config_path="../config", config_name='main', version_base=None)
def makeDataframe(config) -> pd.DataFrame:
    """
    Given paths listed in the config file, generate
    a pandas dataframe with data from files in these
    paths. 
    Returns: Pandas Dataframe Object
    """
    print(config.raw.path)
    raw_path = Path(config.raw.path)
    zones = ".." / raw_path / "zoning.geojson"
    zones = geopandas.read_file(zones)
    return zones

In [6]:
df = makeDataframe(cfg)
df

data/raw/

,shape_st_2,area,shape_stle,blocks_id,perimeter,lasteditor,height,lastupdate,objectid,genplan,zoneclass,new_block,shape_st_1,shape_star,zonedesc,baseelev,zone,geometry
0,897.965039154,256240.562,897.96503916,3,2942.173,None,0,None,1,LDR,R-1H,062 2949,23871.2937675,23871.2939453,None,0,R,"MULTIPOLYGON (((-122.27356 37.90460, -122.2735..."
1,452.362820501,111175,452.3628205,5,1484.545,None,0,None,2,LDR,R-1H,063 2951,10322.7637992,10322.763916,None,0,R,"MULTIPOLYGON (((-122.26997 37.90433, -122.2699..."
2,807.498810905,170184.812,807.49881091,6,2637.073,None,0,None,3,LDR,R-1H,062 2942,16129.8272618,16129.8276367,None,0,R,"MULTIPOLYGON (((-122.27484 37.90388, -122.2745..."
3,1011.43398248,307217.938,1011.43398248,7,3510.71,None,0,None,4,LDR,R-1H,063 3100,28537.9496481,28537.951416,None,0,R,"MULTIPOLYGON (((-122.26898 37.90397, -122.2684..."
4,433.015174892,101674.438,433.01517489,8,1421.052,None,0,None,5,LDR,R-1H,062 2945,9440.55918856,9440.55957031,None,0,R,"MULTIPOLYGON (((-122.27198 37.90388, -122.2719..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1855,338.715577619,157345.375,338.71557762,436,1725.794,None,0,None,1856,M,MULI,060 2355,7153.08030928,7153.08007813,None,0,MULI,"MULTIPOLYGON (((-122.29736 37.88114, -122.2974..."
1856,172.74327643,57831.625,172.74327643,1113,1126.78,None,0,None,1857,M,MULI,054 1763,1228.491685,1228.49169922,None,0,MULI,"MULTIPOLYGON (((-122.28949 37.85835, -122.2893..."
1857,157.757642818,63278.188,381.15307606,1532,1248.658,None,0,None,1858,NC,C-SA,052 1527,335.41452172,6088.6953125,None,0,C,"MULTIPOLYGON (((-122.26951 37.84853, -122.2695..."
1858,105.835958641,77694.688,445.48575821,1556,1456.261,None,0,None,1859,NC,C-AC,052 1435,480.870974915,7457.67993164,None,0,C,"MULTIPOLYGON (((-122.27333 37.84618, -122.2733..."
1859,129.49176163,28538.438,218.92572458,1525,718.455,None,0,None,1860,MDR,R-2A,052 1533,996.79170825,2649.86743164,None,0,R,"MULTIPOLYGON (((-122.27278 37.84918, -122.2732..."